### ISSUE TITLE
Warning installing spacy en language

### ISSUE THREAD

**Issue by lucazav** [alterway/anonymization#2]
Following the code in the readme, you suggest to install the `spacy` english language using this code:

`python -m spacy download en`

When running this, I'm getting the following message:

> As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the full pipeline package name 'en_core_web_sm' instead.

So I had  to run the following code in order to make the example work:

`python -m spacy download en_core_web_lg`

**Comment by Veeraraghavans** [comment]
Thanks for sharing this information. Spacy can download any "en" based language model.  We will update the specific model in the documentation.
