### ISSUE TITLE
Spacy Model

### ISSUE THREAD

**Issue by ramcesit** [alterway/anonymization#3]
Hi, in the sample code provided you have mentioned the usage of a large spacy model.  But in the installation requirement since you have mentioned **python -m spacy download en** which leads to download of **en_core_web_sm**, which is a small spacy model. So kindly change the spacy installation requirement and also update the same in your sample code.

**Comment by Veeraraghavans** [comment]
Thanks @ramcesit for your inputs. Same has been reported in Issue #2  Readme is updated accordingly.
